-- Insertar 10 actores de ejemplo con imágenes placeholder de Unsplash y bloques de información ficticios

INSERT INTO public.actores (nombre, video_url, imagen_principal_url, imagenes_urls, bloques, imagen_principal_index) VALUES
('Juan Pérez', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Protagonista en la serie \"El Refugio\" (Canal 13, 2020-2022). Interpretó el papel de Martín durante 3 temporadas, recibiendo críticas positivas por su desempeño dramático.", "order": 0}, {"tipo": "cine", "contenido": "Actor principal en \"Noche de Luna\" (2019). Película independiente dirigida por Alejandro Santos que participó en varios festivales internacionales.", "order": 1}, {"tipo": "teatro", "contenido": "Participación en obra \"Esperando a Godot\" en Teatro San Martín (2018). Función especial que se extendió por 6 meses.", "order": 2}, {"tipo": "formacion", "contenido": "Egresado de la Escuela Nacional de Arte Dramático (2015). Especialización en actuación teatral y cinematográfica. Talleres de improvisación con reconocidos maestros internacionales.", "order": 3}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Portugués: Intermedio (nivel B2). Francés: Básico (nivel A2).", "order": 4}]'::jsonb,
 0),

('María González', 'https://www.youtube.com/watch?v=jNQXAC9IVRw', 
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Co-protagonista en \"Mujeres de Fuerza\" (Telefe, 2021-actualidad). Serie de drama que aborda temas sociales contemporáneos. Su personaje, Ana, ha sido destacado por la crítica especializada.", "order": 0}, {"tipo": "teatro", "contenido": "Obra \"Hamlet\" en Teatro Nacional (2018). Interpretó el papel de Ofelia junto a un elenco internacional. La producción recibió el premio a mejor obra clásica del año.", "order": 1}, {"tipo": "cine", "contenido": "Papel secundario en \"Hijos del Viento\" (2020). Película documental-ficción que participó en el Festival de Cine de Mar del Plata.", "order": 2}, {"tipo": "publicidades", "contenido": "Campañas publicitarias para marcas reconocidas: L''Oréal (2021), Coca-Cola (2020), Movistar (2019). Experiencia en comerciales de TV y redes sociales.", "order": 3}, {"tipo": "formacion", "contenido": "Licenciatura en Actuación - Universidad Nacional de las Artes (2016). Talleres especializados en dirección de actores y dramaturgia contemporánea.", "order": 4}, {"tipo": "instagram", "contenido": "@mariagonzalez.actriz - 45.2K seguidores. Contenido relacionado con actuación, detrás de escena y vida personal.", "order": 5}]'::jsonb,
 0),

('Carlos Rodríguez', 'https://www.youtube.com/watch?v=9bZkp7q19f0', 
 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Papel secundario en \"El Círculo\" (2020). Thriller psicológico dirigido por Luis Moreno que fue nominado a varios premios internacionales.", "order": 0}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca reconocida de autos (2021). Comercial que se transmitió durante el Super Bowl y alcanzó millones de visualizaciones en redes sociales.", "order": 1}, {"tipo": "television", "contenido": "Participación en serie \"Noche Urbana\" (Canal 9, 2019-2020). Personaje recurrente que apareció en 15 episodios.", "order": 2}, {"tipo": "teatro", "contenido": "Obra \"La Casa de Bernarda Alba\" en Teatro del Sur (2017). Función que se extendió exitosamente por 4 meses.", "order": 3}, {"tipo": "formacion", "contenido": "Talleres de actuación con maestros internacionales: Lee Strasberg Institute (Nueva York, 2018), Royal Academy of Dramatic Art - Curso intensivo (Londres, 2017).", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Italiano: Intermedio (nivel B1).", "order": 5}]'::jsonb,
 0),

('Ana Martínez', 'https://www.youtube.com/watch?v=kJQP7kiw5Fk', 
 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Presentadora en programa matutino \"Buen Día Argentina\" (Canal 7, 2019-2021). Programa de entretenimiento y actualidad que alcanzó altos niveles de audiencia.", "order": 0}, {"tipo": "cine", "contenido": "Protagonista en \"Historias Urbanas\" (2022). Película independiente que fue seleccionada para participar en el Festival Internacional de Cine de Toronto.", "order": 1}, {"tipo": "teatro", "contenido": "Monólogo \"Sola\" en Teatro Rojas (2020). Obra de autoría propia que exploró temas de identidad y género. Recibió elogios de la crítica especializada.", "order": 2}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca de cosméticos (2019-2021). Imagen de marca que incluyó spots televisivos, gráfica y presencia en redes sociales.", "order": 3}, {"tipo": "formacion", "contenido": "Diplomatura en Actuación - Instituto de Artes del Espectáculo (2018). Especialización en teatro contemporáneo y dramaturgia.", "order": 4}, {"tipo": "instagram", "contenido": "@anamartinez.oficial - 128K seguidores. Contenido sobre actuación, lifestyle y colaboraciones con marcas.", "order": 5}, {"tipo": "premios", "contenido": "Mejor Actriz Revelación - Premios Cóndor de Plata 2022. Nominación a Mejor Actriz - Premios Martín Fierro 2021.", "order": 6}]'::jsonb,
 0),

('Diego Fernández', 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', 
 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "teatro", "contenido": "Actor en \"Romeo y Julieta\" - Teatro Colón (2020). Producción moderna de la obra clásica que incorporó elementos contemporáneos. Función de gala presidencial.", "order": 0}, {"tipo": "television", "contenido": "Serie web \"Digital Dreams\" (2021). Plataforma streaming independiente. Su personaje, Lucas, se volvió viral en redes sociales.", "order": 1}, {"tipo": "cine", "contenido": "Cortometraje \"El Último Tren\" (2019). Ganador del Festival Nacional de Cortometrajes. Participó en competencia internacional.", "order": 2}, {"tipo": "formacion", "contenido": "Egresado de la Escuela Nacional de Arte Dramático (2017). Talleres especializados en comedia física y clown. Estudios de danza contemporánea.", "order": 3}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Alemán: Básico (nivel A2).", "order": 4}, {"tipo": "facebook", "contenido": "Diego Fernández - Actor. Página oficial con actualizaciones sobre proyectos y presentaciones teatrales.", "order": 5}]'::jsonb,
 0),

('Laura Sánchez', 'https://www.youtube.com/watch?v=OPf0YbXqDm0', 
 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Protagonista en película independiente \"Reflejos\" (2021). Drama psicológico que exploró temas de memoria y pérdida. La película recibió el premio del jurado en el Festival de Cine Independiente de Buenos Aires.", "order": 0}, {"tipo": "teatro", "contenido": "Monólogo \"Vida en Venta\" (2019). Obra de autoría propia que se presentó en el Festival Internacional de Teatro de Buenos Aires. Posteriormente hizo gira por Latinoamérica.", "order": 1}, {"tipo": "television", "contenido": "Participación especial en serie \"Noches Sin Luna\" (Telefe, 2020). Arco argumental de 8 episodios que recibió atención mediática.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Artes Escénicas - Universidad de Buenos Aires (2018). Maestría en Dirección Teatral (en curso). Talleres con reconocidos directores internacionales.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Actriz - Festival de Cine Independiente de Buenos Aires 2021. Premio Revelación - Asociación de Críticos de Teatro 2019.", "order": 4}, {"tipo": "instagram", "contenido": "@laurasa.actriz - 89.3K seguidores. Contenido sobre proceso creativo, teatro y activismo social.", "order": 5}]'::jsonb,
 0),

('Roberto López', 'https://www.youtube.com/watch?v=L_jWHffIx5E', 
 'https://images.unsplash.com/photo-1517322048670-7e30d3da1356?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1517322048670-7e30d3da1356?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Antagonista principal en \"Noches Oscuras\" (Canal 13, 2020-2022). Serie de suspenso que se convirtió en una de las más vistas de la plataforma. Su personaje, el Doctor Morales, se volvió icónico.", "order": 0}, {"tipo": "publicidades", "contenido": "Voz en off para múltiples campañas publicitarias. Experiencia de más de 10 años en locución comercial para radio, TV y plataformas digitales. Marcas: Samsung, Chevrolet, Banco Santander.", "order": 1}, {"tipo": "cine", "contenido": "Papel de reparto en \"El Juego Final\" (2019). Thriller internacional con elenco de alto nivel. La película fue estrenada en cines de toda Latinoamérica.", "order": 2}, {"tipo": "teatro", "contenido": "Obra \"Macbeth\" en Teatro San Martín (2018). Interpretó el papel titular en una producción innovadora que mezcló teatro tradicional con tecnología moderna.", "order": 3}, {"tipo": "formacion", "contenido": "Egresado del Conservatorio Nacional de Arte Dramático (2012). Especialización en voz y dicción. Talleres de interpretación con maestros de la Royal Shakespeare Company.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1).", "order": 5}, {"tipo": "web-oficial", "contenido": "www.robertolopez.actor - Sitio web oficial con reel, CV completo y galería de trabajos.", "order": 6}]'::jsonb,
 0),

('Sofía Ramírez', 'https://www.youtube.com/watch?v=YQHsXMglC9A', 
 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Papel principal en \"La Última Estación\" (2022). Película de drama histórico que fue seleccionada para participar en el Festival de Cannes - Quincena de Realizadores. Interpretó el personaje de Elena durante toda la narrativa.", "order": 0}, {"tipo": "television", "contenido": "Serie dramática \"Amores Cruzados\" (Netflix, 2021). Co-protagonista junto a reconocidos actores internacionales. La serie fue renovada para una segunda temporada debido a su éxito.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"La Gaviota\" en Teatro Nacional (2020). Adaptación moderna de la obra clásica de Chéjov. Su interpretación de Nina fue destacada por la crítica especializada.", "order": 2}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca de lujo internacional (2021-2022). Imagen de marca que incluyó campañas globales en múltiples países.", "order": 3}, {"tipo": "formacion", "contenido": "Licenciatura en Actuación - Universidad Nacional de las Artes (2019). Intercambio académico en La Sorbonne (París, 2018). Talleres especializados en método Stanislavski.", "order": 4}, {"tipo": "premios", "contenido": "Mejor Actriz - Premios Cóndor de Plata 2022. Nominación a Mejor Actriz - Premios Goya 2022. Revelación del Año - Premios Sur 2021.", "order": 5}, {"tipo": "instagram", "contenido": "@sofiaramirez.actriz - 234K seguidores. Contenido sobre proyectos, viajes y vida personal con enfoque en causas sociales.", "order": 6}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1). Italiano: Intermedio (nivel B2).", "order": 7}]'::jsonb,
 0),

('Martín Torres', 'https://www.youtube.com/watch?v=d-diB65scQU', 
 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "teatro", "contenido": "Director y actor en \"El Laberinto\" (2021). Obra de su autoría que fue estrenada en el Festival Internacional de Teatro de Buenos Aires. La producción exploró temas existenciales a través de una narrativa no lineal.", "order": 0}, {"tipo": "formacion", "contenido": "Egresado de la Escuela Nacional de Arte Dramático (2015). Especialización en dirección teatral. Maestría en Dramaturgia - Universidad Nacional de las Artes (2019). Estudios complementarios en filosofía del arte.", "order": 1}, {"tipo": "cine", "contenido": "Cortometraje \"Despertar\" (2020). Dirigió y protagonizó este proyecto independiente que ganó el premio del público en el Festival de Cortometrajes de Córdoba.", "order": 2}, {"tipo": "television", "contenido": "Serie web \"Fragmentos\" (2019). Plataforma independiente. Creó, dirigió y actuó en este proyecto experimental que exploró nuevos formatos narrativos.", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 15 años de experiencia en teatro, cine y televisión. Ha trabajado en más de 30 producciones teatrales, tanto como actor como director. Fundador de compañía teatral independiente que ha producido 8 obras originales.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2). Portugués: Básico (nivel A2).", "order": 5}, {"tipo": "web-oficial", "contenido": "www.martintorres.teatro - Sitio web con portafolio completo de trabajos, crítica teatral y próximos proyectos.", "order": 6}]'::jsonb,
 0),

('Valentina Cruz', 'https://www.youtube.com/watch?v=hT_nvWreIhg', 
 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Presentadora en programa de entretenimiento \"Noche de Estrellas\" (Canal 7, 2020-actualidad). Programa semanal que se ha convertido en uno de los más populares de la programación nocturna. Conduce entrevistas con personalidades del espectáculo y cultura.", "order": 0}, {"tipo": "cine", "contenido": "Cameo en \"Festival de Verano\" (2021). Comedia romántica que fue un éxito de taquilla. Participó en una escena memorable que se volvió viral en redes sociales.", "order": 1}, {"tipo": "premios", "contenido": "Mejor actriz revelación - Premios Nacionales de Televisión 2020. Nominación a Mejor Presentadora - Premios Martín Fierro 2021 y 2022. Premio del Público - Festival de Cine de Mar del Plata 2021.", "order": 2}, {"tipo": "publicidades", "contenido": "Campañas publicitarias para marcas de moda y belleza (2019-2022). Ha trabajado con reconocidas marcas internacionales como embajadora de imagen.", "order": 3}, {"tipo": "teatro", "contenido": "Musical \"Chicago\" en Teatro Broadway (2018). Interpretó el papel de Roxie Hart en una producción de gran escala que agotó localidades durante 6 meses.", "order": 4}, {"tipo": "formacion", "contenido": "Licenciatura en Comunicación Social - Universidad de Buenos Aires (2017). Formación actoral en diversos talleres especializados. Estudios de canto y danza desde temprana edad.", "order": 5}, {"tipo": "instagram", "contenido": "@valentinacruz.oficial - 312K seguidores. Contenido sobre entretenimiento, moda, lifestyle y detrás de escena de programas de TV.", "order": 6}, {"tipo": "facebook", "contenido": "Valentina Cruz Oficial. Página con actualizaciones sobre programas, proyectos y eventos. 89K seguidores.", "order": 7}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Portugués: Intermedio (nivel B2).", "order": 8}]'::jsonb,
 0);

