-- Insertar 10 guionistas de ejemplo con imágenes placeholder de Unsplash y bloques de información ficticios

INSERT INTO public.guionistas (nombre, video_url, imagen_principal_url, imagenes_urls, bloques, imagen_principal_index, orden) VALUES
('Alejandro Martínez', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Guionista principal de serie \"Crónicas Urbanas\" (Netflix, 2021-2023). Creó y desarrolló la serie durante 3 temporadas, recibiendo premios internacionales.", "order": 0}, {"tipo": "cine", "contenido": "Guionista y director de \"Noche de Luna\" (2019). Película independiente que participó en varios festivales internacionales y ganó el premio al mejor guión.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Esperando a Godot\" - Adaptación moderna (2018). Función especial que se extendió exitosamente por 6 meses en Teatro San Martín.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Letras - Universidad de Buenos Aires (2015). Especialización en guión cinematográfico y televisivo. Master en Dramaturgia (2017).", "order": 3}, {"tipo": "premios", "contenido": "Mejor Guión Original - Premios Cóndor de Plata 2020. Nominación al Emmy Internacional 2022 por mejor serie dramática.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2). Portugués: Básico (nivel A2).", "order": 5}]'::jsonb,
 0, 0),

('María Fernández', 'https://www.youtube.com/watch?v=jNQXAC9IVRw', 
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Guionista de serie \"Vidas Paralelas\" (Telefe, 2022-actualidad). Co-creadora y guionista principal de la serie dramática más vista del año.", "order": 0}, {"tipo": "cine", "contenido": "Guionista de \"El Círculo Perfecto\" (2021). Thriller psicológico que fue nominado a varios premios internacionales y ganó el premio al mejor guión en el Festival de Cine de Mar del Plata.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Casa de Muñecas\" - Adaptación contemporánea (2020). Estrenada en Teatro Nacional con gran éxito de crítica y público.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Artes - Universidad Nacional de las Artes (2016). Especialización en guión cinematográfico. Talleres con reconocidos guionistas internacionales.", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 10 años de experiencia escribiendo para televisión, cine y teatro. Ha trabajado en más de 20 proyectos audiovisuales.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Italiano: Intermedio (nivel B1).", "order": 5}]'::jsonb,
 0, 1),

('Carlos Rodríguez', 'https://www.youtube.com/watch?v=9bZkp7q19f0', 
 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Guionista y director de \"Historias Urbanas\" (2022). Película independiente que fue seleccionada para participar en el Festival Internacional de Cine de Toronto y ganó el premio del jurado.", "order": 0}, {"tipo": "television", "contenido": "Guionista de serie web \"Digital Dreams\" (2021). Plataforma streaming independiente que se volvió viral en redes sociales.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Sola\" - Monólogo original (2020). Estrenada en Teatro Rojas, exploró temas de identidad y género con gran éxito.", "order": 2}, {"tipo": "formacion", "contenido": "Diplomatura en Guión - Instituto de Artes del Espectáculo (2018). Especialización en guión para series de televisión. Estudios complementarios en narrativa contemporánea.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Guión Original - Festival de Cine Independiente de Buenos Aires 2022. Premio Revelación - Asociación de Guionistas 2021.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2).", "order": 5}]'::jsonb,
 0, 2),

('Ana González', 'https://www.youtube.com/watch?v=kJQP7kiw5Fk', 
 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Guionista principal de programa matutino \"Buen Día Argentina\" (Canal 7, 2019-2021). Programa de entretenimiento y actualidad que alcanzó altos niveles de audiencia.", "order": 0}, {"tipo": "cine", "contenido": "Guionista de \"Reflejos\" (2021). Drama psicológico que exploró temas de memoria y pérdida. Ganó el premio del jurado en el Festival de Cine Independiente de Buenos Aires.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Vida en Venta\" (2019). Monólogo de autoría propia que se presentó en el Festival Internacional de Teatro de Buenos Aires y posteriormente hizo gira por Latinoamérica.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Artes Escénicas - Universidad de Buenos Aires (2018). Maestría en Guión Cinematográfico (en curso). Talleres con reconocidos guionistas internacionales.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Guión - Festival de Cine Independiente de Buenos Aires 2021. Premio Revelación - Asociación de Guionistas 2019.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Portugués: Intermedio (nivel B2).", "order": 5}]'::jsonb,
 0, 3),

('Diego López', 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', 
 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "teatro", "contenido": "Guionista y director de \"Romeo y Julieta\" - Producción moderna (2020). Estrenada en Teatro Colón con gran éxito. Función de gala presidencial.", "order": 0}, {"tipo": "television", "contenido": "Guionista de serie \"Noches Sin Luna\" (Telefe, 2020). Arco argumental de 8 episodios que recibió atención mediática.", "order": 1}, {"tipo": "cine", "contenido": "Guionista de cortometraje \"El Último Tren\" (2019). Ganador del Festival Nacional de Cortometrajes y participó en competencia internacional.", "order": 2}, {"tipo": "formacion", "contenido": "Egresado de la Escuela Nacional de Arte Dramático (2017). Especialización en dramaturgia contemporánea. Estudios de narrativa audiovisual.", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 12 años de experiencia escribiendo para teatro, cine y televisión. Ha trabajado en más de 25 producciones.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Alemán: Básico (nivel A2).", "order": 5}]'::jsonb,
 0, 4),

('Laura Sánchez', 'https://www.youtube.com/watch?v=OPf0YbXqDm0', 
 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Guionista y directora de \"La Última Estación\" (2022). Película de drama histórico que fue seleccionada para participar en el Festival de Cannes - Quincena de Realizadores.", "order": 0}, {"tipo": "television", "contenido": "Guionista de serie dramática \"Amores Cruzados\" (Netflix, 2021). Co-creadora junto a reconocidos actores internacionales. La serie fue renovada para una segunda temporada debido a su éxito.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"La Gaviota\" - Adaptación moderna (2020). Estrenada en Teatro Nacional. Su adaptación fue destacada por la crítica especializada.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Actuación - Universidad Nacional de las Artes (2019). Intercambio académico en La Sorbonne (París, 2018). Especialización en guión cinematográfico.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Guión - Premios Cóndor de Plata 2022. Nominación al Premio Goya 2022. Revelación del Año - Premios Sur 2021.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1). Italiano: Intermedio (nivel B2).", "order": 5}]'::jsonb,
 0, 5),

('Roberto Silva', 'https://www.youtube.com/watch?v=L_jWHffIx5E', 
 'https://images.unsplash.com/photo-1517322048670-7e30d3da1356?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1517322048670-7e30d3da1356?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Guionista principal de serie \"Noches Oscuras\" (Canal 13, 2020-2022). Serie de suspenso que se convirtió en una de las más vistas de la plataforma. Creador y showrunner.", "order": 0}, {"tipo": "cine", "contenido": "Guionista de \"El Juego Final\" (2019). Thriller internacional con elenco de alto nivel. La película fue estrenada en cines de toda Latinoamérica.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Macbeth\" - Adaptación innovadora (2018). Estrenada en Teatro San Martín. La producción mezcló teatro tradicional con tecnología moderna.", "order": 2}, {"tipo": "formacion", "contenido": "Egresado del Conservatorio Nacional de Arte Dramático (2012). Especialización en guión para series de televisión. Master en Narrativa Audiovisual (2015).", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 15 años de experiencia escribiendo para televisión, cine y teatro. Ha creado y desarrollado 5 series de televisión exitosas.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1).", "order": 5}]'::jsonb,
 0, 6),

('Sofía Torres', 'https://www.youtube.com/watch?v=YQHsXMglC9A', 
 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Guionista de \"El Laberinto\" (2021). Película independiente que exploró temas existenciales a través de una narrativa no lineal. Ganó el premio del público en el Festival de Cine de Córdoba.", "order": 0}, {"tipo": "television", "contenido": "Guionista de serie web \"Fragmentos\" (2019). Plataforma independiente. Creó este proyecto experimental que exploró nuevos formatos narrativos.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Despertar\" (2020). Monólogo original que ganó el premio del público en el Festival de Cortometrajes de Córdoba.", "order": 2}, {"tipo": "formacion", "contenido": "Egresada de la Escuela Nacional de Arte Dramático (2015). Especialización en dramaturgia. Maestría en Guión Cinematográfico - Universidad Nacional de las Artes (2019).", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 10 años de experiencia en teatro, cine y televisión. Ha trabajado en más de 30 producciones como guionista.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2). Portugués: Básico (nivel A2).", "order": 5}]'::jsonb,
 0, 7),

('Martín Pérez', 'https://www.youtube.com/watch?v=d-diB65scQU', 
 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Guionista de serie \"Las Hijas de la Ciudad\" (Netflix, 2021-2023). Co-creador y guionista principal durante 2 temporadas.", "order": 0}, {"tipo": "cine", "contenido": "Guionista de \"Sueños Rotos\" (2020). Película independiente que ganó el premio del público en el Festival de Cine de Buenos Aires.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"La Casa de los Espíritus\" (2019). Adaptación teatral que se estrenó en Teatro Colón con gran éxito.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Letras - Universidad de Buenos Aires (2018). Especialización en guión cinematográfico y televisivo.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Guión Original - Festival de Cine de Buenos Aires 2020. Nominación al Emmy Internacional 2022.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2).", "order": 5}]'::jsonb,
 0, 8),

('Valentina Ramírez', 'https://www.youtube.com/watch?v=hT_nvWreIhg', 
 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Guionista de programa de entretenimiento \"Noche de Estrellas\" (Canal 7, 2020-actualidad). Programa semanal muy popular con altos niveles de audiencia.", "order": 0}, {"tipo": "cine", "contenido": "Guionista de \"Festival de Verano\" (2021). Comedia romántica que fue un éxito de taquilla. Participó en una escena memorable que se volvió viral.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Chicago\" - Adaptación musical (2018). Musical que agotó localidades durante 6 meses en Teatro Broadway.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Comunicación Social - Universidad de Buenos Aires (2017). Formación en guión en diversos talleres especializados.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Guión - Premios Nacionales de Televisión 2020. Nominación a Mejor Guión - Premios Martín Fierro 2021 y 2022.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Portugués: Intermedio (nivel B2).", "order": 5}]'::jsonb,
 0, 9);

