-- Insertar 10 actrices de ejemplo con imágenes placeholder de Unsplash y bloques de información ficticios

INSERT INTO public.actrices (nombre, video_url, imagen_principal_url, imagenes_urls, bloques, imagen_principal_index, orden) VALUES
('Agustina Scuderi', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Protagonista en serie \"Las Hijas de la Ciudad\" (Netflix, 2021-2023). Interpretó el papel de Valeria durante 2 temporadas, recibiendo reconocimiento internacional por su actuación.", "order": 0}, {"tipo": "cine", "contenido": "Actriz principal en \"Sueños Rotos\" (2020). Película independiente que ganó el premio del público en el Festival de Cine de Buenos Aires.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"La Casa de los Espíritus\" en Teatro Colón (2019). Función especial que se extendió exitosamente por 4 meses.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Actuación - Universidad Nacional de las Artes (2018). Especialización en teatro contemporáneo y dramaturgia.", "order": 3}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2). Italiano: Básico (nivel A2).", "order": 4}]'::jsonb,
 0, 0),

('Andrea Pietra', 'https://www.youtube.com/watch?v=jNQXAC9IVRw', 
 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Co-protagonista en \"Vidas Paralelas\" (Telefe, 2022-actualidad). Serie dramática que aborda temas sociales contemporáneos.", "order": 0}, {"tipo": "cine", "contenido": "Papel secundario en \"El Círculo Perfecto\" (2021). Thriller psicológico que participó en varios festivales internacionales.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"Casa de Muñecas\" en Teatro Nacional (2020). Interpretó el papel de Nora con gran éxito de crítica.", "order": 2}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca de perfumería internacional (2021-2022). Imagen de marca reconocida globalmente.", "order": 3}, {"tipo": "formacion", "contenido": "Diplomatura en Actuación - Instituto de Artes del Espectáculo (2019). Talleres especializados en método Stanislavski.", "order": 4}, {"tipo": "instagram", "contenido": "@andreapietra.actriz - 67.5K seguidores. Contenido sobre actuación, moda y vida personal.", "order": 5}]'::jsonb,
 0, 1),

('Camila Rabinovich', 'https://www.youtube.com/watch?v=9bZkp7q19f0', 
 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Presentadora en programa de entretenimiento \"Noche de Estrellas\" (Canal 7, 2020-actualidad). Programa semanal que se ha convertido en uno de los más populares de la programación nocturna.", "order": 0}, {"tipo": "cine", "contenido": "Protagonista en \"Historias Urbanas\" (2022). Película independiente que fue seleccionada para participar en el Festival Internacional de Cine de Toronto.", "order": 1}, {"tipo": "teatro", "contenido": "Monólogo \"Sola\" en Teatro Rojas (2020). Obra de autoría propia que exploró temas de identidad y género.", "order": 2}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca de cosméticos (2019-2021). Imagen de marca que incluyó spots televisivos y presencia en redes sociales.", "order": 3}, {"tipo": "formacion", "contenido": "Egresada de la Escuela Nacional de Arte Dramático (2017). Especialización en actuación cinematográfica.", "order": 4}, {"tipo": "premios", "contenido": "Mejor Actriz Revelación - Premios Cóndor de Plata 2022. Nominación a Mejor Actriz - Premios Martín Fierro 2021.", "order": 5}, {"tipo": "instagram", "contenido": "@camilarabinovich.oficial - 145K seguidores. Contenido sobre actuación, lifestyle y colaboraciones con marcas.", "order": 6}]'::jsonb,
 0, 2),

('Carla Pantanali', 'https://www.youtube.com/watch?v=kJQP7kiw5Fk', 
 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Antagonista principal en \"Noches Oscuras\" (Canal 13, 2020-2022). Serie de suspenso que se convirtió en una de las más vistas de la plataforma.", "order": 0}, {"tipo": "cine", "contenido": "Papel principal en \"La Última Estación\" (2022). Película de drama histórico que fue seleccionada para participar en el Festival de Cannes.", "order": 1}, {"tipo": "teatro", "contenido": "Obra \"La Gaviota\" en Teatro Nacional (2020). Adaptación moderna de la obra clásica de Chéjov.", "order": 2}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca de lujo internacional (2021-2022). Imagen de marca que incluyó campañas globales.", "order": 3}, {"tipo": "formacion", "contenido": "Licenciatura en Actuación - Universidad Nacional de las Artes (2019). Intercambio académico en La Sorbonne (París, 2018).", "order": 4}, {"tipo": "premios", "contenido": "Mejor Actriz - Premios Cóndor de Plata 2022. Nominación a Mejor Actriz - Premios Goya 2022.", "order": 5}]'::jsonb,
 0, 3),

('Cecilia Cambiaso', 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', 
 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1463453091185-61582044d556?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "teatro", "contenido": "Directora y actriz en \"El Laberinto\" (2021). Obra de su autoría que fue estrenada en el Festival Internacional de Teatro de Buenos Aires.", "order": 0}, {"tipo": "formacion", "contenido": "Egresada de la Escuela Nacional de Arte Dramático (2015). Especialización en dirección teatral. Maestría en Dramaturgia - Universidad Nacional de las Artes (2019).", "order": 1}, {"tipo": "cine", "contenido": "Cortometraje \"Despertar\" (2020). Dirigió y protagonizó este proyecto independiente que ganó el premio del público.", "order": 2}, {"tipo": "television", "contenido": "Serie web \"Fragmentos\" (2019). Plataforma independiente. Creó, dirigió y actuó en este proyecto experimental.", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 15 años de experiencia en teatro, cine y televisión. Ha trabajado en más de 30 producciones teatrales.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2).", "order": 5}]'::jsonb,
 0, 4),

('Cecilia Rossetto', 'https://www.youtube.com/watch?v=OPf0YbXqDm0', 
 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Presentadora en programa de entretenimiento \"Noche de Estrellas\" (Canal 7, 2020-actualidad). Programa semanal muy popular.", "order": 0}, {"tipo": "cine", "contenido": "Cameo en \"Festival de Verano\" (2021). Comedia romántica que fue un éxito de taquilla.", "order": 1}, {"tipo": "premios", "contenido": "Mejor actriz revelación - Premios Nacionales de Televisión 2020. Nominación a Mejor Presentadora - Premios Martín Fierro 2021 y 2022.", "order": 2}, {"tipo": "publicidades", "contenido": "Campañas publicitarias para marcas de moda y belleza (2019-2022). Ha trabajado con reconocidas marcas internacionales.", "order": 3}, {"tipo": "teatro", "contenido": "Musical \"Chicago\" en Teatro Broadway (2018). Interpretó el papel de Roxie Hart durante 6 meses.", "order": 4}, {"tipo": "formacion", "contenido": "Licenciatura en Comunicación Social - Universidad de Buenos Aires (2017). Formación actoral en diversos talleres especializados.", "order": 5}]'::jsonb,
 0, 5),

('Clara Saccone', 'https://www.youtube.com/watch?v=L_jWHffIx5E', 
 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Protagonista en serie \"El Refugio\" (Canal 13, 2020-2022). Interpretó el papel de Sofía durante 3 temporadas.", "order": 0}, {"tipo": "cine", "contenido": "Actriz principal en \"Noche de Luna\" (2019). Película independiente dirigida por Alejandro Santos.", "order": 1}, {"tipo": "teatro", "contenido": "Participación en obra \"Esperando a Godot\" en Teatro San Martín (2018). Función especial que se extendió por 6 meses.", "order": 2}, {"tipo": "formacion", "contenido": "Egresada de la Escuela Nacional de Arte Dramático (2015). Especialización en actuación teatral y cinematográfica.", "order": 3}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Portugués: Intermedio (nivel B2).", "order": 4}]'::jsonb,
 0, 6),

('Cristina Fridman', 'https://www.youtube.com/watch?v=YQHsXMglC9A', 
 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Papel secundario en \"El Círculo\" (2020). Thriller psicológico dirigido por Luis Moreno que fue nominado a varios premios.", "order": 0}, {"tipo": "publicidades", "contenido": "Campaña publicitaria para marca reconocida de autos (2021). Comercial que se transmitió durante el Super Bowl.", "order": 1}, {"tipo": "television", "contenido": "Participación en serie \"Noche Urbana\" (Canal 9, 2019-2020). Personaje recurrente que apareció en 15 episodios.", "order": 2}, {"tipo": "teatro", "contenido": "Obra \"La Casa de Bernarda Alba\" en Teatro del Sur (2017). Función que se extendió exitosamente por 4 meses.", "order": 3}, {"tipo": "formacion", "contenido": "Talleres de actuación con maestros internacionales: Lee Strasberg Institute (Nueva York, 2018).", "order": 4}]'::jsonb,
 0, 7),

('Daniela Flombaum', 'https://www.youtube.com/watch?v=d-diB65scQU', 
 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "teatro", "contenido": "Actor en \"Romeo y Julieta\" - Teatro Colón (2020). Producción moderna de la obra clásica que incorporó elementos contemporáneos.", "order": 0}, {"tipo": "television", "contenido": "Serie web \"Digital Dreams\" (2021). Plataforma streaming independiente. Su personaje se volvió viral en redes sociales.", "order": 1}, {"tipo": "cine", "contenido": "Cortometraje \"El Último Tren\" (2019). Ganador del Festival Nacional de Cortometrajes.", "order": 2}, {"tipo": "formacion", "contenido": "Egresada de la Escuela Nacional de Arte Dramático (2017). Talleres especializados en comedia física y clown.", "order": 3}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Alemán: Básico (nivel A2).", "order": 4}]'::jsonb,
 0, 8),

('Diana Lamas', 'https://www.youtube.com/watch?v=hT_nvWreIhg', 
 'https://images.unsplash.com/photo-1517322048670-7e30d3da1356?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1517322048670-7e30d3da1356?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "television", "contenido": "Antagonista principal en \"Noches Oscuras\" (Canal 13, 2020-2022). Serie de suspenso muy popular.", "order": 0}, {"tipo": "publicidades", "contenido": "Voz en off para múltiples campañas publicitarias. Experiencia de más de 10 años en locución comercial.", "order": 1}, {"tipo": "cine", "contenido": "Papel de reparto en \"El Juego Final\" (2019). Thriller internacional con elenco de alto nivel.", "order": 2}, {"tipo": "teatro", "contenido": "Obra \"Macbeth\" en Teatro San Martín (2018). Interpretó el papel titular en una producción innovadora.", "order": 3}, {"tipo": "formacion", "contenido": "Egresada del Conservatorio Nacional de Arte Dramático (2012). Especialización en voz y dicción.", "order": 4}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1).", "order": 5}]'::jsonb,
 0, 9);

