-- Insertar 5 directores de ejemplo con imágenes placeholder de Unsplash y bloques de información ficticios

INSERT INTO public.directores (nombre, video_url, imagen_principal_url, imagenes_urls, bloques, imagen_principal_index, orden) VALUES
('Luis Moreno', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Director de \"El Círculo\" (2020). Thriller psicológico que fue nominado a varios premios internacionales y ganó el premio a mejor dirección en el Festival de Cine de Mar del Plata.", "order": 0}, {"tipo": "television", "contenido": "Director general de serie \"Noches Oscuras\" (Canal 13, 2020-2022). Serie de suspenso que se convirtió en una de las más vistas de la plataforma. Dirigió 25 episodios durante 3 temporadas.", "order": 1}, {"tipo": "teatro", "contenido": "Director de obra \"Macbeth\" en Teatro San Martín (2018). Producción innovadora que mezcló teatro tradicional con tecnología moderna. La obra se extendió exitosamente por 6 meses.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Cinematografía - Universidad Nacional de las Artes (2012). Especialización en dirección cinematográfica. Master en Dirección de Cine - Universidad de Nueva York (2015).", "order": 3}, {"tipo": "premios", "contenido": "Mejor Director - Premios Cóndor de Plata 2020. Nominación a Mejor Director - Premios Goya 2021. Premio a la Mejor Dirección - Festival de Cine de Mar del Plata 2020.", "order": 4}, {"tipo": "experiencia", "contenido": "Más de 15 años de experiencia dirigiendo cine, televisión y teatro. Ha dirigido más de 40 proyectos audiovisuales, incluyendo 3 largometrajes y 2 series de televisión exitosas.", "order": 5}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1).", "order": 6}]'::jsonb,
 0, 0),

('Sofia González', 'https://www.youtube.com/watch?v=jNQXAC9IVRw', 
 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Directora de \"Historias Urbanas\" (2022). Película independiente que fue seleccionada para participar en el Festival Internacional de Cine de Toronto y ganó el premio del jurado. Su dirección fue destacada por la crítica especializada.", "order": 0}, {"tipo": "television", "contenido": "Directora de serie dramática \"Amores Cruzados\" (Netflix, 2021). Co-creadora junto a reconocidos actores internacionales. Dirigió los primeros 8 episodios. La serie fue renovada para una segunda temporada debido a su éxito.", "order": 1}, {"tipo": "teatro", "contenido": "Directora de obra \"La Gaviota\" en Teatro Nacional (2020). Adaptación moderna de la obra clásica de Chéjov. Su dirección innovadora fue destacada por la crítica especializada.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Dirección Teatral - Universidad Nacional de las Artes (2016). Intercambio académico en La Sorbonne (París, 2018). Especialización en dirección cinematográfica con método Stanislavski.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Directora - Premios Cóndor de Plata 2022. Nominación a Mejor Directora - Premios Goya 2022. Revelación del Año - Premios Sur 2021.", "order": 4}, {"tipo": "experiencia", "contenido": "Más de 12 años de experiencia dirigiendo teatro, cine y televisión. Ha dirigido más de 30 producciones teatrales y 5 proyectos cinematográficos.", "order": 5}, {"tipo": "idiomas", "contenido": "Inglés: Nativo. Español: Nativo. Francés: Fluido (nivel C1). Italiano: Intermedio (nivel B2).", "order": 6}]'::jsonb,
 0, 1),

('Carlos Martínez', 'https://www.youtube.com/watch?v=9bZkp7q19f0', 
 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Director de \"Reflejos\" (2021). Drama psicológico que exploró temas de memoria y pérdida. La película recibió el premio del jurado en el Festival de Cine Independiente de Buenos Aires y ganó el premio a mejor dirección.", "order": 0}, {"tipo": "television", "contenido": "Director de serie \"Vidas Paralelas\" (Telefe, 2022-actualidad). Serie dramática más vista del año. Ha dirigido 12 episodios durante la primera temporada.", "order": 1}, {"tipo": "teatro", "contenido": "Director de monólogo \"Vida en Venta\" (2019). Obra de autoría propia que se presentó en el Festival Internacional de Teatro de Buenos Aires. Posteriormente hizo gira por Latinoamérica.", "order": 2}, {"tipo": "formacion", "contenido": "Licenciatura en Artes Escénicas - Universidad de Buenos Aires (2015). Maestría en Dirección Teatral (2018). Talleres con reconocidos directores internacionales.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Director - Festival de Cine Independiente de Buenos Aires 2021. Premio Revelación - Asociación de Directores 2019.", "order": 4}, {"tipo": "experiencia", "contenido": "Más de 10 años de experiencia dirigiendo cine, televisión y teatro. Ha dirigido más de 25 producciones, incluyendo 2 largometrajes independientes.", "order": 5}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2).", "order": 6}]'::jsonb,
 0, 2),

('Ana López', 'https://www.youtube.com/watch?v=kJQP7kiw5Fk', 
 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "cine", "contenido": "Directora de \"La Última Estación\" (2022). Película de drama histórico que fue seleccionada para participar en el Festival de Cannes - Quincena de Realizadores. Su dirección fue elogiada por la crítica internacional.", "order": 0}, {"tipo": "television", "contenido": "Directora de serie web \"Digital Dreams\" (2021). Plataforma streaming independiente. Su dirección innovadora hizo que el proyecto se volviera viral en redes sociales.", "order": 1}, {"tipo": "teatro", "contenido": "Directora de \"Romeo y Julieta\" - Producción moderna (2020). Estrenada en Teatro Colón con gran éxito. Función de gala presidencial. La producción incorporó elementos contemporáneos.", "order": 2}, {"tipo": "formacion", "contenido": "Diplomatura en Dirección - Instituto de Artes del Espectáculo (2017). Especialización en dirección cinematográfica. Estudios complementarios en narrativa visual.", "order": 3}, {"tipo": "premios", "contenido": "Mejor Directora - Premios Cóndor de Plata 2022. Nominación a Mejor Directora - Premios Goya 2022. Premio del Público - Festival de Cine de Mar del Plata 2021.", "order": 4}, {"tipo": "experiencia", "contenido": "Más de 8 años de experiencia dirigiendo teatro, cine y televisión. Ha dirigido más de 20 producciones teatrales y 3 proyectos cinematográficos.", "order": 5}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Portugués: Intermedio (nivel B2).", "order": 6}]'::jsonb,
 0, 3),

('Roberto Fernández', 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ', 
 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop',
 '["https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&h=600&fit=crop"]'::jsonb,
 '[{"tipo": "teatro", "contenido": "Director y dramaturgo de \"El Laberinto\" (2021). Obra de su autoría que fue estrenada en el Festival Internacional de Teatro de Buenos Aires. La producción exploró temas existenciales a través de una narrativa no lineal y ganó el premio del público.", "order": 0}, {"tipo": "cine", "contenido": "Director de cortometraje \"Despertar\" (2020). Proyecto independiente que ganó el premio del público en el Festival de Cortometrajes de Córdoba y participó en competencia internacional.", "order": 1}, {"tipo": "television", "contenido": "Director de serie web \"Fragmentos\" (2019). Plataforma independiente. Creó, dirigió y escribió este proyecto experimental que exploró nuevos formatos narrativos.", "order": 2}, {"tipo": "formacion", "contenido": "Egresado de la Escuela Nacional de Arte Dramático (2014). Especialización en dirección teatral. Maestría en Dramaturgia - Universidad Nacional de las Artes (2018). Estudios complementarios en filosofía del arte.", "order": 3}, {"tipo": "experiencia", "contenido": "Más de 18 años de experiencia en teatro, cine y televisión. Ha dirigido más de 40 producciones teatrales, tanto como director como dramaturgo. Fundador de compañía teatral independiente que ha producido 10 obras originales.", "order": 4}, {"tipo": "premios", "contenido": "Mejor Director - Festival Internacional de Teatro de Buenos Aires 2021. Premio Revelación - Asociación de Directores 2019.", "order": 5}, {"tipo": "idiomas", "contenido": "Inglés: Fluido (nivel C1). Francés: Intermedio (nivel B2). Portugués: Básico (nivel A2).", "order": 6}]'::jsonb,
 0, 4);

